#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('Acacha llum illuminates your laravel packages', '0.1');
$app->add(new Acacha\Llum\Console\SqliteCommand);
$app->add(new Acacha\Llum\Console\SqliteTouchCommand);
$app->add(new Acacha\Llum\Console\SqliteEnvCommand);

$app->run();
